export { MERLIN_LOGO_CORNER_RADIUS, MERLIN_LOGO_PALETTE, MERLIN_LOGO_VIEWBOX } from './palette';
export {
  MERLIN_BUBBLE_AO_ARC,
  MERLIN_BUBBLE_HIGHLIGHT_ARC,
  MERLIN_STAR_EDGE_LEFT,
  MERLIN_STAR_EDGE_RIGHT,
  MERLIN_STAR_INNER,
  MERLIN_STAR_OUTER,
  MERLIN_STAR_SHINE,
} from './paths';
export { renderMerlinLogoStaticSvg } from './renderStaticSvg';